### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by jlaurencin** [bndw/wifi-card#307]
Is it possible to have a docker-compose.yml file for local installation?

**Comment by Technetium1** [comment]
There is already a Dockerfile: https://github.com/bndw/wifi-card/blob/master/Dockerfile
Compose is only required for multi-container apps.

**Comment by xHyperElectric** [comment]
> I came to check on this as well, docker compose info would be awesome.

```yaml

  wifi-card:
    image: bndw/wifi-card:latest
    container_name: wifi-card
    restart: unless-stopped
    ports:
      - 80:80
```
